# Continuous integration (CI) triggers cause a build to run whenever a push is made to the specified branches
# or a specified tag is pushed.
# YAML builds are configured by default with a CI trigger on all branches.
trigger:
  batch: "false"
  branches:
    include:
    - master
    - develop
  paths:
    exclude:
    - README.md
    - docs

# A pull request will not trigger a build
pr: none

# If your pipeline has templates in another repository, you must let the system know about that repository.
# The repository resource lets you specify an external repository.
# In this case "self" means "the repository that the YAML file is in". Though it
# should not be necessary.
resources:
  repositories:
    - repository: self

variables:
- group: vars
- name: LinuxPoolName
  value: 'ubuntu-16.04'
- name: WinPoolName
  value: 'windows-2019'
- name: terraformstoragerg
  value: 'terraformrg'
- name: terraformstorageaccount
  value: 'terraformstoragestv22f79'
- name: tfstoragecontainername
  value: 'terraform'
- name: serviceConnection
  value: 'aks_sc'
- name: aksclustername
  value: 'stvaks1'
- name: aksrgname
  value: 'stvRG1'
- name: ClientID
  value: 'http://tfm-k8s-spn'
- name: storagekey
  value: 'willbefetchedbyscript'
- name: tf_key
  value: 'terraform.tfstate'
- name: tf_container_name
  value: 'terraform'
- name: resource_location
  value: 'eastus'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(LinuxPoolName)
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Terraform files to artifacts'
      inputs:
        SourceFolder: terraform
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

    - task: CopyFiles@2
      displayName: 'Copy K8s YAML files to artifacts'
      inputs:
        SourceFolder: manifests
        TargetFolder: '$(Build.ArtifactStagingDirectory)/manifests'

    - task: CopyFiles@2
      displayName: 'Copy Scripts to artifacts'
      inputs:
        SourceFolder: scripts
        TargetFolder: '$(Build.ArtifactStagingDirectory)/scripts'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Provision
  jobs:
    # track deployments on the environment
  - deployment: 'Provision'
    pool:
      vmImage: $(LinuxPoolName)
    # creates an environment if it doesn’t exist
    environment: 'dev'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          # the following script will create an Azure resource group, Storage account and Storage container which will be used to store terraform remote state
          - task: AzureCLI@1
            displayName: 'Provision Storage for TF State'
            inputs:
              azureSubscription: '$(serviceConnection)'
              scriptLocation: 'scriptPath'
              scriptPath: '$(Pipeline.Workspace)/drop/scripts/Create-TerraformStateStorage.sh'

          - task: AzurePowerShell@4
            displayName: 'Get TF State Storage Key'
            inputs:
              azureSubscription: '$(serviceConnection)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/drop/scripts/Get-StorageKey.ps1'
              azurePowerShellVersion: 'latestVersion'

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in **/*.tf'
            inputs:
              targetFiles: '$(Pipeline.Workspace)/drop/Terraform/*.tf'
              escapeType: none
              tokenPrefix: '__'
              tokenSuffix: '__'

          # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          #   displayName: 'Install Terraform 0.12.7'
          #   inputs:
          #     terraformVersion: 0.12.7

- stage: Deploy
  jobs:
    # track deployments on the environment
  - deployment: 'Deploy'
    pool:
      vmImage: $(WinPoolName)
    # creates an environment if it doesn’t exist
    environment: 'dev'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - task: Terraform@2
            displayName: 'Terraform Init'
            inputs:
              TemplatePath: '$(Pipeline.Workspace)/drop/Terraform'
              Arguments: 'init'
              InstallTerraform: true
              UseAzureSub: true
              ConnectedServiceNameARM: $(serviceConnection)

          # - task: Terraform@2
          #   displayName: 'Terraform Plan'
          #   inputs:
          #     TemplatePath: '$(Pipeline.Workspace)/drop/Terraform'
          #     Arguments: 'plan'
          #     InstallTerraform: true
          #     UseAzureSub: true
          #     ConnectedServiceNameARM: $(serviceConnection)

          - task: Terraform@2
            displayName: 'Terraform Apply -auto-approve'
            inputs:
              TemplatePath: '$(Pipeline.Workspace)/drop/Terraform'
              Arguments: 'apply -auto-approve'
              InstallTerraform: true
              UseAzureSub: true
              ConnectedServiceNameARM: $(serviceConnection)

          - task: KubectlInstaller@0
            displayName: 'Install Kubectl latest'

          - task: Kubernetes@1
            displayName: 'kubectl - (Resource Manager) Deploy nginxdemo Deployment'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: '$(serviceConnection)'
              azureResourceGroup: '$(aksrgname)'
              kubernetesCluster: '$(aksclustername)'
              command: apply
              arguments: '-f $(Pipeline.Workspace)/drop/manifests/deployment.yml'

          - task: Kubernetes@1
            displayName: 'kubectl - (Resource Manager) Deploy nginxdemo Service'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: '$(serviceConnection)'
              azureResourceGroup: '$(aksrgname)'
              kubernetesCluster: '$(aksclustername)'
              command: apply
              arguments: '-f $(Pipeline.Workspace)/drop/manifests/service.yml'