trigger:
  batch: "true"
  branches:
    include:
    - master
    - develop

# A pull request will not trigger a build
pr: none

resources:
- repo: self

variables:
  poolName: 'Hosted VS2017'
  terraformstoragerg: 'terraformrg'
  terraformstorageaccount: 'terraformstoragestv22f79'
  serviceConnection: 'aks_sc'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      name: $(poolName)
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Terraform files to artifacts'
      inputs:
        SourceFolder: terraform
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Terraform'

    - task: CopyFiles@2
      displayName: 'Copy K8s YAML files to artifacts'
      inputs:
        SourceFolder: manifests
        TargetFolder: '$(Build.ArtifactStagingDirectory)/manifests'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

- stage: Deploy
  jobs:
    # track deployments on the environment
  - deployment: 'NginxDemo_Release_Pipeline'
    pool:
      name: $(poolName)
    # creates an environment if it doesn’t exist
    environment: 'dev'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@1
            displayName: 'Azure CLI to deploy Storage for Terraform Remote'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptLocation: inlineScript
              inlineScript: |
                # the following script will create an Azure resource group, Storage account and Storage container which will be used to store terraform remote state

                call az group create --location eastus --name $(terraformstoragerg)

                call az storage account create --name $(terraformstorageaccount) --resource-group $(terraformstoragerg) --location eastus --sku Standard_LRS

                call az storage container create --name terraform --account-name $(terraformstorageaccount)
